// OfflineEmbedder.swift
//
// Wraps the bundled SigLIP-2 CoreML model so iOS can produce
// 768-dimensional image embeddings entirely on-device. The model
// (siglip2_base_patch16_384.mlpackage, 177MB FP16) lives in
// PopAlphaCore/Resources/Models/ — gitignored, regenerated by
// `cog/siglip-features/coreml_convert.py`.
//
// Pipeline:
//     UIImage / CGImage
//        ↓ resize to 384×384 RGB (CoreML's ImageType expects fixed shape)
//     CVPixelBuffer  (kCVPixelFormatType_32BGRA)
//        ↓ MLModel.prediction(input:)
//     MLMultiArray (1, 768)
//        ↓ extract Float
//     [Float]  (L2-normalized inside the CoreML graph; see
//              SiglipVisionEmbedder.forward in coreml_convert.py)
//
// The CoreML model has the SigLIP normalization
// (scale=1/127.5, bias=[-1,-1,-1]) baked into its ImageType input,
// so Swift only needs to provide an RGB pixel buffer in [0, 255].
// Don't pre-normalize on Swift side or you'll double-shift.
//
// Performance budget:
//     - First inference (cold): ~50-200ms (model load + first run on
//       Neural Engine)
//     - Subsequent inferences (warm): ~50-100ms on iPhone NE
//     - Mac CPU validation (coreml_convert.py): 29.5ms — iPhone NE
//       should be in this ballpark or faster.
//
// Thread-safety: MLModel is thread-safe for inference. Concurrent
// queries against the same OfflineEmbedder instance are safe. Hold
// one shared instance app-wide.

import CoreML
import CoreVideo
import Foundation
import UIKit

public enum OfflineEmbedderError: Error, LocalizedError {
    case modelNotFoundInBundle
    case modelLoadFailed(Error)
    case imageTooSmall(width: Int, height: Int)
    case pixelBufferAllocationFailed
    case inferenceFailed(Error)
    case malformedOutput(String)

    public var errorDescription: String? {
        switch self {
        case .modelNotFoundInBundle:
            return "siglip2_base_patch16_384.mlmodelc not found in PopAlphaCore bundle. Regenerate with cog/siglip-features/coreml_convert.py."
        case .modelLoadFailed(let err):
            return "Failed to load SigLIP CoreML model: \(err.localizedDescription)"
        case .imageTooSmall(let w, let h):
            return "Source image too small for SigLIP (\(w)×\(h)); need at least 1×1."
        case .pixelBufferAllocationFailed:
            return "Failed to allocate CVPixelBuffer for SigLIP input."
        case .inferenceFailed(let err):
            return "CoreML inference failed: \(err.localizedDescription)"
        case .malformedOutput(let detail):
            return "CoreML output unexpected: \(detail)"
        }
    }
}

public final class OfflineEmbedder {
    public static let inputDimension = 384  // SigLIP-2-Base-384 expects 384×384
    public static let outputDimension = 768

    private let model: MLModel
    private let inputFeatureName: String
    private let outputFeatureName: String

    /// Initialize with the bundled CoreML model. Loads from
    /// `Bundle.module` (the Swift Package's resource bundle).
    /// Throws if the .mlmodelc isn't present (developers need to run
    /// `coreml_convert.py` first — see Models/.gitignore).
    public init() throws {
        // Xcode compiles .mlpackage → .mlmodelc at build time. SPM's
        // `process(...)` resource handling does the same. The bundled
        // model name matches the source filename without extension.
        let modelName = "siglip2_base_patch16_384"

        guard let url = Bundle.module.url(forResource: modelName, withExtension: "mlmodelc") else {
            // Fallback: try .mlpackage path (some Xcode setups don't
            // pre-compile during dev builds).
            guard let pkg = Bundle.module.url(forResource: modelName, withExtension: "mlpackage") else {
                throw OfflineEmbedderError.modelNotFoundInBundle
            }
            do {
                let cfg = MLModelConfiguration()
                cfg.computeUnits = Self.preferredComputeUnits()
                self.model = try MLModel(contentsOf: pkg, configuration: cfg)
            } catch {
                throw OfflineEmbedderError.modelLoadFailed(error)
            }
            self.inputFeatureName = Self.detectInputFeatureName(model: self.model)
            self.outputFeatureName = Self.detectOutputFeatureName(model: self.model)
            return
        }

        do {
            let cfg = MLModelConfiguration()
            cfg.computeUnits = Self.preferredComputeUnits()
            self.model = try MLModel(contentsOf: url, configuration: cfg)
        } catch {
            throw OfflineEmbedderError.modelLoadFailed(error)
        }
        self.inputFeatureName = Self.detectInputFeatureName(model: self.model)
        self.outputFeatureName = Self.detectOutputFeatureName(model: self.model)
    }

    /// `.all` (Neural Engine + GPU + CPU) on real devices, but the
    /// iOS Simulator has no Neural Engine and its GPU path silently
    /// outputs zeros for FP16 SigLIP-2 (verified via direct
    /// MLMultiArray inspection — pixel buffer is correct, output is
    /// all-zero across 768 elements). Falling back to `.cpuOnly` on
    /// simulator gets correct embeddings without changing real-device
    /// behavior.
    private static func preferredComputeUnits() -> MLComputeUnits {
        #if targetEnvironment(simulator)
        return .cpuOnly
        #else
        return .all
        #endif
    }

    /// Embed a UIImage. Resizes to 384×384 RGB internally; the
    /// CoreML model's baked-in normalization handles
    /// uint8 → fp [-1, 1].
    public func embed(image: UIImage) throws -> [Float] {
        guard image.size.width > 0, image.size.height > 0 else {
            throw OfflineEmbedderError.imageTooSmall(
                width: Int(image.size.width),
                height: Int(image.size.height),
            )
        }
        let pixelBuffer = try Self.makePixelBuffer(image: image, side: Self.inputDimension)
        return try embed(pixelBuffer: pixelBuffer)
    }

    /// Embed a pre-resized CVPixelBuffer. Skips the resize step —
    /// useful when the camera capture already produced a 384×384
    /// buffer (future optimization for the live scanner).
    public func embed(pixelBuffer: CVPixelBuffer) throws -> [Float] {
        #if DEBUG
        // One-shot pixel-buffer sanity print so we can tell
        // "input is bad" from "model output is bad" in the smoke test.
        Self.dumpPixelBufferStatsOnce(pixelBuffer)
        #endif
        let inputs = try MLDictionaryFeatureProvider(dictionary: [
            inputFeatureName: MLFeatureValue(pixelBuffer: pixelBuffer),
        ])
        do {
            let prediction = try model.prediction(from: inputs)
            #if DEBUG
            Self.dumpPredictionStatsOnce(prediction, outputName: outputFeatureName)
            #endif
            return try Self.extractEmbedding(
                from: prediction,
                outputName: outputFeatureName,
            )
        } catch let err as OfflineEmbedderError {
            throw err
        } catch {
            throw OfflineEmbedderError.inferenceFailed(error)
        }
    }

    #if DEBUG
    private static var debugDumped = false
    private static let debugDumpLock = NSLock()

    /// Prints mean R/G/B and a few sample pixels from the input buffer.
    /// Fires once per process lifetime so we don't spam every frame in
    /// production builds (and DEBUG-only anyway).
    private static func dumpPixelBufferStatsOnce(_ pb: CVPixelBuffer) {
        debugDumpLock.lock()
        let alreadyDumped = debugDumped
        debugDumpLock.unlock()
        if alreadyDumped { return }

        CVPixelBufferLockBaseAddress(pb, [.readOnly])
        defer { CVPixelBufferUnlockBaseAddress(pb, [.readOnly]) }

        let w = CVPixelBufferGetWidth(pb)
        let h = CVPixelBufferGetHeight(pb)
        let stride = CVPixelBufferGetBytesPerRow(pb)
        let pixfmt = CVPixelBufferGetPixelFormatType(pb)
        guard let base = CVPixelBufferGetBaseAddress(pb) else {
            print("[embedder.debug] pixelBuffer base addr nil")
            return
        }
        let ptr = base.bindMemory(to: UInt8.self, capacity: stride * h)
        var sumB: UInt64 = 0, sumG: UInt64 = 0, sumR: UInt64 = 0
        for y in 0..<h {
            for x in 0..<w {
                let off = y * stride + x * 4
                sumB += UInt64(ptr[off])
                sumG += UInt64(ptr[off + 1])
                sumR += UInt64(ptr[off + 2])
            }
        }
        let n = UInt64(w * h)
        let fmtStr = String(
            format: "%c%c%c%c",
            UInt8((pixfmt >> 24) & 0xFF),
            UInt8((pixfmt >> 16) & 0xFF),
            UInt8((pixfmt >> 8) & 0xFF),
            UInt8(pixfmt & 0xFF),
        )
        print("[embedder.debug] pixelBuffer \(w)×\(h) fmt=\(fmtStr) stride=\(stride) meanB=\(sumB/n) meanG=\(sumG/n) meanR=\(sumR/n)")
    }

    /// Prints output spec + a few raw values from the prediction so
    /// we can diagnose "MLMultiArray reads as zeros" failures.
    private static func dumpPredictionStatsOnce(_ pred: MLFeatureProvider, outputName: String) {
        debugDumpLock.lock()
        let alreadyDumped = debugDumped
        if !alreadyDumped { debugDumped = true }
        debugDumpLock.unlock()
        if alreadyDumped { return }

        guard let v = pred.featureValue(for: outputName) else {
            print("[embedder.debug] no feature \(outputName); names=\(pred.featureNames)")
            return
        }
        guard let arr = v.multiArrayValue else {
            print("[embedder.debug] feature \(outputName) is not multiarray (type=\(v.type))")
            return
        }
        let rawDtype = arr.dataType.rawValue
        var samples: [String] = []
        for i in 0..<min(8, arr.count) {
            samples.append(String(format: "%.4f", arr[i].floatValue))
        }
        print("[embedder.debug] output shape=\(arr.shape) strides=\(arr.strides) dtype=raw=\(rawDtype) count=\(arr.count) first8=[\(samples.joined(separator: ", "))]")
    }
    #endif

    // MARK: - Pixel buffer construction

    /// Resizes a UIImage to a square `side × side` BGRA pixel buffer,
    /// suitable for CoreML's ImageType input. Uses CoreGraphics to
    /// handle orientation + colorspace correctly.
    private static func makePixelBuffer(image: UIImage, side: Int) throws -> CVPixelBuffer {
        let attrs: [CFString: Any] = [
            kCVPixelBufferCGImageCompatibilityKey: true,
            kCVPixelBufferCGBitmapContextCompatibilityKey: true,
        ]
        var pb: CVPixelBuffer?
        let status = CVPixelBufferCreate(
            kCFAllocatorDefault,
            side, side,
            kCVPixelFormatType_32BGRA,
            attrs as CFDictionary,
            &pb,
        )
        guard status == kCVReturnSuccess, let pixelBuffer = pb else {
            throw OfflineEmbedderError.pixelBufferAllocationFailed
        }

        CVPixelBufferLockBaseAddress(pixelBuffer, [])
        defer { CVPixelBufferUnlockBaseAddress(pixelBuffer, []) }

        let baseAddr = CVPixelBufferGetBaseAddress(pixelBuffer)
        let bytesPerRow = CVPixelBufferGetBytesPerRow(pixelBuffer)
        let colorSpace = CGColorSpaceCreateDeviceRGB()
        // BGRA + premultipliedFirst is the kCVPixelFormatType_32BGRA layout.
        let bitmapInfo = CGBitmapInfo.byteOrder32Little.rawValue
            | CGImageAlphaInfo.premultipliedFirst.rawValue

        guard let ctx = CGContext(
            data: baseAddr,
            width: side,
            height: side,
            bitsPerComponent: 8,
            bytesPerRow: bytesPerRow,
            space: colorSpace,
            bitmapInfo: bitmapInfo,
        ) else {
            throw OfflineEmbedderError.pixelBufferAllocationFailed
        }

        // Flip Y because CoreGraphics origin is bottom-left, UIImage
        // expects top-left. Without this the image would render
        // upside-down inside the CoreML input.
        ctx.translateBy(x: 0, y: CGFloat(side))
        ctx.scaleBy(x: 1.0, y: -1.0)

        // Draw the UIImage scaled to side×side. UIGraphicsPushContext
        // installs ctx as the current UI context so UIImage.draw uses
        // it correctly.
        UIGraphicsPushContext(ctx)
        image.draw(in: CGRect(x: 0, y: 0, width: side, height: side))
        UIGraphicsPopContext()

        return pixelBuffer
    }

    // MARK: - Output extraction

    private static func extractEmbedding(
        from prediction: MLFeatureProvider,
        outputName: String,
    ) throws -> [Float] {
        guard let value = prediction.featureValue(for: outputName) else {
            throw OfflineEmbedderError.malformedOutput(
                "no feature named \(outputName) in prediction; got \(prediction.featureNames)",
            )
        }
        guard let array = value.multiArrayValue else {
            throw OfflineEmbedderError.malformedOutput(
                "output \(outputName) is not an MLMultiArray (type=\(value.type))",
            )
        }

        // Validate shape — CoreML can return (1, 768) or (768,) depending
        // on how the conversion sliced singleton dims.
        let count = array.count
        guard count == Self.outputDimension else {
            throw OfflineEmbedderError.malformedOutput(
                "expected \(Self.outputDimension) elements, got \(count) (shape=\(array.shape))",
            )
        }

        var out = [Float](repeating: 0, count: Self.outputDimension)
        // MLMultiArray dataType could be float32 or float16 depending on
        // the conversion's `compute_precision`. Handle both.
        //
        // Use NSNumber subscripts (not raw dataPointer) because
        // MLMultiArray with shape [1, 768] has strides [768, 1] — the
        // raw pointer is contiguous in this case, but the safer API
        // hides shape/stride bugs that Apple sometimes exposes when
        // CoreML adds singleton dims (e.g., outputs of [1, 1, 768]).
        // Subscript-based access on simulator-CPU also reliably reads
        // fp16 outputs that the dataPointer raw read returns as zeros.
        switch array.dataType {
        case .float32:
            for i in 0..<count {
                out[i] = array[i].floatValue
            }
        case .float16:
            for i in 0..<count {
                out[i] = array[i].floatValue
            }
        case .double:
            for i in 0..<count {
                out[i] = Float(array[i].doubleValue)
            }
        default:
            throw OfflineEmbedderError.malformedOutput(
                "unsupported output dataType \(array.dataType)",
            )
        }
        return out
    }

    // MARK: - Feature-name discovery

    /// Auto-detects the input feature name. Our `coreml_convert.py`
    /// names it `image`, but in case the conversion ever changes
    /// (e.g. multi-input variant), pick the first IMAGE-typed input.
    private static func detectInputFeatureName(model: MLModel) -> String {
        let desc = model.modelDescription
        for (name, feat) in desc.inputDescriptionsByName {
            if feat.type == .image { return name }
        }
        return desc.inputDescriptionsByName.keys.first ?? "image"
    }

    /// Auto-detects the output feature name. Our converter outputs
    /// `embedding`. Fallback to the first multi-array output.
    private static func detectOutputFeatureName(model: MLModel) -> String {
        let desc = model.modelDescription
        if let v = desc.outputDescriptionsByName["embedding"] {
            _ = v
            return "embedding"
        }
        for (name, feat) in desc.outputDescriptionsByName {
            if feat.type == .multiArray { return name }
        }
        return desc.outputDescriptionsByName.keys.first ?? "embedding"
    }
}
