-- 20260304150000_profile_social_and_mentions.sql
-- Adds profile follows, public profile views, and structured card mentions on posts.

CREATE TABLE IF NOT EXISTS public.profile_follows (
  follower_id TEXT NOT NULL REFERENCES public.app_users(clerk_user_id) ON DELETE CASCADE,
  followee_id TEXT NOT NULL REFERENCES public.app_users(clerk_user_id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  PRIMARY KEY (follower_id, followee_id),
  CONSTRAINT profile_follows_not_self CHECK (follower_id <> followee_id)
);

CREATE INDEX IF NOT EXISTS profile_follows_followee_idx
  ON public.profile_follows (followee_id, created_at DESC);

CREATE INDEX IF NOT EXISTS profile_follows_follower_idx
  ON public.profile_follows (follower_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.profile_post_card_mentions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES public.profile_posts(id) ON DELETE CASCADE,
  canonical_slug TEXT NOT NULL REFERENCES public.canonical_cards(slug) ON DELETE CASCADE,
  mention_text TEXT NOT NULL,
  start_index INT NOT NULL,
  end_index INT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS profile_post_mentions_post_idx
  ON public.profile_post_card_mentions (post_id, start_index ASC);

CREATE INDEX IF NOT EXISTS profile_post_mentions_card_idx
  ON public.profile_post_card_mentions (canonical_slug, created_at DESC);

DROP VIEW IF EXISTS public.public_user_profiles;
CREATE VIEW public.public_user_profiles AS
SELECT
  handle,
  handle_norm,
  created_at,
  profile_bio,
  profile_banner_url
FROM public.app_users
WHERE handle IS NOT NULL;

GRANT SELECT ON public.public_user_profiles TO anon, authenticated;

DROP VIEW IF EXISTS public.public_profile_posts;
CREATE VIEW public.public_profile_posts AS
SELECT
  pp.id,
  au.handle,
  pp.body,
  pp.created_at
FROM public.profile_posts pp
JOIN public.app_users au
  ON au.clerk_user_id = pp.owner_id
WHERE au.handle IS NOT NULL;

GRANT SELECT ON public.public_profile_posts TO anon, authenticated;

DROP VIEW IF EXISTS public.public_profile_social_stats;
CREATE VIEW public.public_profile_social_stats AS
WITH post_counts AS (
  SELECT owner_id, COUNT(*)::INT AS post_count
  FROM public.profile_posts
  GROUP BY owner_id
),
follower_counts AS (
  SELECT followee_id AS owner_id, COUNT(*)::INT AS follower_count
  FROM public.profile_follows
  GROUP BY followee_id
),
following_counts AS (
  SELECT follower_id AS owner_id, COUNT(*)::INT AS following_count
  FROM public.profile_follows
  GROUP BY follower_id
)
SELECT
  au.clerk_user_id,
  au.handle,
  COALESCE(pc.post_count, 0) AS post_count,
  COALESCE(fc.follower_count, 0) AS follower_count,
  COALESCE(fgc.following_count, 0) AS following_count
FROM public.app_users au
LEFT JOIN post_counts pc ON pc.owner_id = au.clerk_user_id
LEFT JOIN follower_counts fc ON fc.owner_id = au.clerk_user_id
LEFT JOIN following_counts fgc ON fgc.owner_id = au.clerk_user_id;

GRANT SELECT ON public.public_profile_social_stats TO anon, authenticated;

DROP VIEW IF EXISTS public.public_profile_post_mentions;
CREATE VIEW public.public_profile_post_mentions AS
SELECT
  pm.post_id,
  pm.canonical_slug,
  pm.mention_text,
  pm.start_index,
  pm.end_index
FROM public.profile_post_card_mentions pm
JOIN public.profile_posts pp
  ON pp.id = pm.post_id
JOIN public.app_users au
  ON au.clerk_user_id = pp.owner_id
WHERE au.handle IS NOT NULL;

GRANT SELECT ON public.public_profile_post_mentions TO anon, authenticated;
