-- 20260304130000_card_page_views.sql
-- Tracks canonical card page views as an append-only event stream so the app can
-- measure which cards are being visited most and render a daily views chart.

CREATE TABLE IF NOT EXISTS public.card_page_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  canonical_slug TEXT NOT NULL REFERENCES public.canonical_cards(slug) ON DELETE CASCADE,
  viewed_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS card_page_views_slug_viewed_at_idx
  ON public.card_page_views (canonical_slug, viewed_at DESC);

CREATE INDEX IF NOT EXISTS card_page_views_viewed_at_idx
  ON public.card_page_views (viewed_at DESC);

CREATE OR REPLACE FUNCTION public.record_card_page_view(p_canonical_slug TEXT)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_slug TEXT;
  v_id BIGINT;
BEGIN
  v_slug := btrim(coalesce(p_canonical_slug, ''));
  IF v_slug = '' THEN
    RAISE EXCEPTION 'Missing canonical slug.';
  END IF;

  INSERT INTO public.card_page_views (canonical_slug)
  VALUES (v_slug)
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

REVOKE ALL ON FUNCTION public.record_card_page_view(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.record_card_page_view(TEXT) TO anon, authenticated;

DROP VIEW IF EXISTS public.public_card_page_view_daily;
CREATE VIEW public.public_card_page_view_daily AS
SELECT
  canonical_slug,
  (timezone('utc', viewed_at))::date AS view_date,
  COUNT(*)::INT AS views
FROM public.card_page_views
GROUP BY canonical_slug, (timezone('utc', viewed_at))::date;

GRANT SELECT ON public.public_card_page_view_daily TO anon, authenticated;

DROP VIEW IF EXISTS public.public_card_page_view_totals;
CREATE VIEW public.public_card_page_view_totals AS
SELECT
  canonical_slug,
  COUNT(*)::INT AS total_views,
  MAX(viewed_at) AS last_viewed_at
FROM public.card_page_views
GROUP BY canonical_slug;

GRANT SELECT ON public.public_card_page_view_totals TO anon, authenticated;
