-- 20260304140000_profile_features.sql
-- Persistent app-owned profile fields plus a simple activity feed.

ALTER TABLE public.app_users
  ADD COLUMN IF NOT EXISTS profile_bio TEXT,
  ADD COLUMN IF NOT EXISTS profile_banner_url TEXT;

CREATE TABLE IF NOT EXISTS public.profile_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id TEXT NOT NULL REFERENCES public.app_users(clerk_user_id) ON DELETE CASCADE,
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  CONSTRAINT profile_posts_body_length CHECK (char_length(body) BETWEEN 1 AND 280)
);

CREATE INDEX IF NOT EXISTS profile_posts_owner_created_idx
  ON public.profile_posts (owner_id, created_at DESC);
